name: hmsmt
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: 4.6.6
  flutter: 
    sdk: flutter
  image_picker: ^1.0.8
  camera: ^0.10.6
  google_ml_kit: ^0.18.0
  image: ^4.1.7
  image_size_getter: ^2.1.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
 

flutter: 
  uses-material-design: true
  assets:
    - assets/models/


